Repository lakshya125/py_beginners, pull requests merged in 2020-10, with the labels that each got.

#8 Created decimal_to_binary.py
  decimal_to_binary.py
Labels: hacktoberfest-accepted

#7 Create prime.py
  prime.py
Labels: hacktoberfest-accepted

#6 Create binary_to_decimal.py
  binary_to_decimal.py
Labels: hacktoberfest-accepted

#17 #5 - Improve Readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create Hello_World.py
  Hello_World.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Create Armstrong_Number.py
  # Python program to check if the number is an Armstrong number or not  # take input from the user num = int(input("Enter a number: "))  # initialize sum sum = 0  # find the sum of the cube of each digit temp = num while temp > 0:    digit = temp % 10    sum += digit ** 3    temp/Armstrong_Number.py
Labels: hacktoberfest, hacktoberfest-accepted

#24 Create Pants_Pyramid_patter.py
  Pants_Pyramid_patter.py
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create palindrome_no_chk.py
  palindrome_no_chk.py
Labels: hacktoberfest, hacktoberfest-accepted

#20 Create queue.py
  queue.py
Labels: hacktoberfest, hacktoberfest-accepted

#25 Create Timer_prog.py
  Timer_prog.py
Labels: hacktoberfest, hacktoberfest-accepted

#26 Create palindrome_string_chk.py
  palindrome_string_chk.py
Labels: hacktoberfest, hacktoberfest-accepted

#28 Factorial program uploaded
  factorial.py
Labels: hacktoberfest, hacktoberfest-accepted

#30 created a reverse_integer.py file for hacktoberfest submission
  reverse_integer.py
Labels: hacktoberfest, hacktoberfest-accepted

#32 update table of contents (fix #29)
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#41 Created the string_permutations file
  string_permutations.py
Labels: hacktoberfest, hacktoberfest-accepted

#34 feat: add reverse string
  __pycache__/queue.cpython-38.pyc
  alarm_clock.py
Labels: hacktoberfest, hacktoberfest-accepted

#39 Multiple methods for reversing a string in python
  reverse_string.py
Labels: hacktoberfest, hacktoberfest-accepted

#44 Create Hashing.py
  hashing.py
Labels: hacktoberfest, hacktoberfest-accepted

#43 added famous river swimmer problem
  river_swimmer_problem.py
Labels: hacktoberfest, hacktoberfest-accepted

#45 Speech To Text & Text To Speech Example
  VoiceIO/main/speechInput.txt
  VoiceIO/main/speechOutput.txt
  VoiceIO/main/voiceInput.py
  VoiceIO/main/voiceOutput.py
  VoiceIO/requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added number_of_occurences_of_items_in_array.py
  count_occurences_of_items_in_array.py
Labels: hacktoberfest, hacktoberfest-accepted

#48 added file details to README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#49 Initial commit game
  word game.py
Labels: hacktoberfest, hacktoberfest-accepted, python

#54 QuickSort program added
  QuickSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#58 Update readme
  README.md
  word_game.py
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#60 adding a quadratic equation solution
  quadratic_equation.py
Labels: hacktoberfest, hacktoberfest-accepted, python

#65 Create Pythagorean_Triples
  Pythagorean_Triples
Labels: hacktoberfest, hacktoberfest-accepted

#59 Hangman Game
  hangman.py
  hangman_words.py
Labels: Good work, hacktoberfest, hacktoberfest-accepted, python

#57 Add basic program for stack
  stack.py
Labels: hacktoberfest, hacktoberfest-accepted, python

#62 Create LongestSubstringWithoutRepeatingCharacters.py
  LongestSubstringWithoutRepeatingCharacters.py
Labels: hacktoberfest, hacktoberfest-accepted, python

#63 adding find connected_components_using_dfs
  count_connected_components_in_graph.py
Labels: hacktoberfest, hacktoberfest-accepted, python

#64 Create YouTube video downloader.py
  YouTube video downloader.py
Labels: Good work, hacktoberfest, hacktoberfest-accepted

#66 Create MakeListofCSV
  MakeListofCSV
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, python

#67 Create Rearrange_Digits_Into_Largest_Possible_Value
  Rearrange_Digits_Into_Largest_Possible_Value
Labels: Good work, hacktoberfest, hacktoberfest-accepted

#69 Create Pig_Latin
  Pig_Latin
Labels: hacktoberfest, hacktoberfest-accepted

#76 Added binary search program in python
  binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted

#81 Added RomanToInteger.py
  RomanToInteger.py
Labels: hacktoberfest, hacktoberfest-accepted

#68 Create guessnumber.py
  guessnumber.py
Labels: hacktoberfest, hacktoberfest-accepted

#78 Added AdditonOfDigitsOfAGivenNumber.py
  AdditonOfDigitsOfAGivenNumber.py
  CountingOccurrenceOfEachWord.py
Labels: hacktoberfest, hacktoberfest-accepted

#82 Added Leibniz'sFormulaForCalculatingPi.py
  Leibniz'sFormulaForCalculatingPi.py
Labels: hacktoberfest, hacktoberfest-accepted

#74 unit_matrix
  unit matrix.py
Labels: hacktoberfest, hacktoberfest-accepted

#77 Added program to compute Eulers totient function
  euler_totient.py
Labels: hacktoberfest, hacktoberfest-accepted

#79 Added DoublyLinkedList.py
  DoublyLinkedList.py
Labels: hacktoberfest, hacktoberfest-accepted

#72 Created recursion.py
  recursion.py
  recursion_roman_doll_exp.py
Labels: hacktoberfest, hacktoberfest-accepted

#80 Added KaperkerNumbers.py
  KaperkerNumbers.py
Labels: hacktoberfest, hacktoberfest-accepted

#83 Added python program to send email
  send_mail.py
Labels: Good work, hacktoberfest, hacktoberfest-accepted

#75 Added K-Means Algorithm
  K-Means.py
Labels: hacktoberfest, hacktoberfest-accepted

#87 Create Arithmetic Progression
  Arithmetic Progression
Labels: hacktoberfest, hacktoberfest-accepted

#99 Create discount_calculator.py
  discount_calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#97 Added rainbow_hex script for issue #93
  README.md
  __pycache__/rainbow_hex.cpython-38.pyc
  rainbow_hex.py
Labels: Good work, hacktoberfest, hacktoberfest-accepted

#105 add fizz-buzz
  fizz-buzz.py
Labels: Good work, hacktoberfest, hacktoberfest-accepted

#106 Dijkstra’s shortest path algorithm
  Dijkstra’s_shortest_path_algorithm.py
Labels: hacktoberfest, hacktoberfest-accepted

#111 webBlocker.py
  app.py
Labels: hacktoberfest, hacktoberfest-accepted

#116 Tic Tac Toe Game.py
  Tic Tac Toe Game.py
Labels: hacktoberfest, hacktoberfest-accepted

#117 Mad Libs Generator.py
  Mad Libs Generator.py
Labels: hacktoberfest, hacktoberfest-accepted

#96 add Linear Search
  linearSearch.py
Labels: hacktoberfest, hacktoberfest-accepted

#102 added selection sort
  selection_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#121 Finds anagrams within an array
  Anagrams.py
Labels: hacktoberfest, hacktoberfest-accepted

#128 Added 4 files to tables of contents
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#124 Create all_rotations_of_a_string.py
  all_rotations_of_a_string.py
Labels: hacktoberfest, hacktoberfest-accepted

#125 json-sample files added
  json.py
Labels: hacktoberfest, hacktoberfest-accepted

#127 Added GCD of two numbers code
  GCD_recursion.py
Labels: hacktoberfest, hacktoberfest-accepted

#130 Added Power of a number code
  power_recursion.py
Labels: hacktoberfest, hacktoberfest-accepted

#136 Create distance_functions.py
  distance_functions.py
Labels: hacktoberfest, hacktoberfest-accepted

#133 Created a Seconds to Minutes converter
  Seconds_to_Minutes.py
Labels: hacktoberfest-accepted

#132 Create second_lowest_element.py
  second_lowest_element.py
Labels: hacktoberfest-accepted

#141 Create checkletter.py
  checkletter.py
Labels: Good work, hacktoberfest, hacktoberfest-accepted

#144 Create numsort.py
  numsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#142 Create exact_change.py
  exact_change.py
Labels: hacktoberfest, hacktoberfest-accepted

#148 Monocity of an Array
  MonotonicArray.py
Labels: hacktoberfest, hacktoberfest-accepted

#150 Add python program to convert degrees to radians
  degree_to_radian.py
Labels: hacktoberfest, hacktoberfest-accepted

#147 Change palindrome check condition for string
  palindrome_string_chk.py
Labels: hacktoberfest-accepted
